# Generated by Django 4.2.5 on 2023-09-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofiletable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiletable',
            old_name='Goal_DeathLine',
            new_name='Goal_Deadline',
        ),
        migrations.RenameField(
            model_name='userprofiletable',
            old_name='Skill_set',
            new_name='Skill_Set',
        ),
        migrations.AlterField(
            model_name='userprofiletable',
            name='Job',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
