# Generated by Django 4.2.5 on 2023-09-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_goal_deathline_userprofiletable_goal_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiletable',
            name='Needs_Visa_Sponsorship',
            field=models.CharField(max_length=300),
        ),
    ]
