# Generated by Django 4.2.5 on 2023-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0002_auto_20210717_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="special_event_code",
            field=models.IntegerField(default=0),
        ),
    ]
